###############################################################################
#
#    Service Config section
#
###############################################################################
server:
  port: 9990,9991,9992,9993
  mode: debug  # debug;release
  gorm:
    LogMode: false # db log
  view:
    limit: 10 
  
ethereum:
  chainID: 1
  host: https://mainnet.infura.io/1UoO4I
  address: "0x762009cd5dcabb5a125008d70f5efdbdff2aa782"
  passphrase: "613131313131"  # rand

###############################################################################
#
#    MariaDb Config section
#
###############################################################################

database:
  dialect: mysql
  database: oneyuan
  user: root
  password: yiyun88
  # 要支持emoji的话，填 utf8mb4
  charset: utf8mb4
  # 数据库ip 
  host: 127.0.0.1
  # 数据库端口
  port: 3306
  # 空闲时最大的连接数
  maxIdleConns: 20
  # 最大的连接数
  maxOpenConns: 20  

