
### eth_getTransactionByHash
POST https://mainnet.infura.io/1UoO4I
Content-Type: application/json

{
    "jsonrpc":"2.0",
    "method":"eth_getTransactionByHash",
    "params":["0x802a072a303a1bb19a20065a262526f2cfda0d1ea16eeb3db6500d9d06f65963"],
    "id":67
}

### eth_getTransactionByHash
POST http://123.206.29.15:8540
Content-Type: application/json

{
    "jsonrpc":"2.0",
    "method":"eth_getTransactionByHash",
    "params":["0xd3d2990862f00de9482d72a6d59cb69b818439f524bcdf90c5df93b8cd4b3e55"],
    "id":67
}

### eth_getTransactionReceipt
POST https://mainnet.infura.io/1UoO4I
Content-Type: application/json

{
    "jsonrpc":"2.0",
    "method":"eth_getTransactionReceipt",
    "params":["0x802a072a303a1bb19a20065a262526f2cfda0d1ea16eeb3db6500d9d06f65963"],
    "id":67
}

### eth_getTransactionReceipt
POST http://127.0.0.1:8540
Content-Type: application/json

{
    "jsonrpc":"2.0",
    "method":"eth_getTransactionReceipt",
    "params":["0x79f5203f0bdeb6cb9392d00c170c1e29a61ed28fcfad6e378524b1b14ae8e60e"],
    "id":67
}


